# Generated by Django 2.2.4 on 2019-08-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('filepath', models.CharField(max_length=200)),
                ('client_ip', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
    ]
